### ISSUE TITLE
Problem from start

### ISSUE THREAD

**Issue by Freddereck** [itskdhere/ChatGPT-Discord-BOT#13]
root@vm4103082:~/GPT4# npm run start

> chatgpt-discord-bot@3.0.0 start
> node index.js

(node:1115818) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError: Cannot read properties of undefined (reading 'toLocaleLowerCase')
    at initOpenAI (file:///root/GPT4/index.js:55:32)
    at main (file:///root/GPT4/index.js:123:21)

**Comment by itskdhere** [comment]
Probably this got solved on Discord. So closing it.
