### ISSUE TITLE
Update: Add Support for ChatGPT-API-V4

### ISSUE THREAD

**Issue by topapoo** [itskdhere/ChatGPT-Discord-BOT#2]
### **Add Support for ChatGPT API V4**

With the update of the api [ChatGPT API](https://github.com/transitive-bullshit/chatgpt-api) I would like the code to be updated to the latest version of [ChatGPT API](https://github.com/transitive-bullshit/chatgpt-api) as it offers new ways to support the openai language.

```ts
import { ChatGPTAPI } from 'chatgpt'

const api = new ChatGPTAPI({
  apiKey: process.env.OPENAI_API_KEY
})

const res = await api.sendMessage('Hello World!')
console.log(res.text)
```

Please upgrade to `chatgpt@latest` (at least [v4.0.0](https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.0.0)). The updated version is **significantly more lightweight and robust** compared with previous versions. You also don't have to worry about IP issues or rate limiting :)

## Usage

Sign up for an [OpenAI API key](https://platform.openai.com/overview) and store it in your environment.

```ts
import { ChatGPTAPI } from 'chatgpt'

async function example() {
  const api = new ChatGPTAPI({
    apiKey: process.env.OPENAI_API_KEY
  })

  const res = await api.sendMessage('Hello World!')
  console.log(res.text)
}
```

**Comment by itskdhere** [comment]
Currently [chatgpt-api v4](https://github.com/transitive-bullshit/chatgpt-api) uses paid gpt-3 model ( `text-davinci-003` ) and if the community discovers some leaked model that gets blocked by OpenAI within 2-3 days.
So its not worth upgrading to [v4](https://github.com/transitive-bullshit/chatgpt-api) 😪
