### ISSUE TITLE
Case sensitive on font 'univers' 

### ISSUE THREAD

**Issue by just-rich** [itskdhere/ChatGPT-Discord-BOT#4]
Line 251 need to change `univers` to `Univers`

Also guessing this isn't for a headless browser?

**Comment by itskdhere** [comment]
> Line 251 need to change `univers` to `Univers`

Thanks for identifying this. Both works fine for me btw.  But I'll change it to `Univers` on the next release.

---
> Also guessing this isn't for a headless browser?

Can you please explain what do you mean by `this` ?  the repo or the font ?

**Comment by just-rich** [comment]
> Can you please explain what do you mean by `this` ? the repo or the font ?

This needs a GUI to work right? It opens a browser window? So a VPS without a GUI that can't open browser windows, this won't run on. Would need to use a headless browser like chromium

**Comment by itskdhere** [comment]
> This needs a GUI to work right? It opens a browser window?

Yes, this is the default.


> So a VPS without a GUI that can't open browser windows, this won't run on. Would need to use a headless browser like chromium

Headless mode may work if there's no CAPTCHA.

**Comment by just-rich** [comment]
> Headless mode may work if there's no CAPTCHA.

Captcha for what?

**Comment by itskdhere** [comment]
Actually `Cloudflare Turnstile`, not CAPTCHA, sorry.
This challenge is shown before the login page, if you're tying to login too frequently.

Also currently [ChatGPT](https://chat.openai.com/) is at capacity.

**Comment by itskdhere** [comment]
Changed the font: b0fc49f03e46b6612d803f7910a8a110a138c5b1
Thanks @just-rich 🙏
